server {
    listen 80;
    client_max_body_size 200m;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    location /api/crawler/ {
        proxy_pass http://behavior-consumer:9105/api/crawler/;
        proxy_set_header Host $host;
    }

    location /api/music/ {
        proxy_pass http://behavior-consumer:9105;
        proxy_set_header Host $host;
    }

    location /music/ {
        alias /data/music/;
        types {
            audio/mp4 m4a m4s;
            audio/mpeg mp3;
        }
        add_header Accept-Ranges bytes;
    }

    location /api/ {
        proxy_pass http://gateway-service:9100;
        proxy_set_header Host $host;
    }
}
