server {
    listen 80;
    client_max_body_size 200m;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/crawler/ {
        proxy_pass http://behavior-consumer:9105/api/crawler/;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://gateway-service:9100;
        proxy_set_header Host $host;
    }
}
