server:
  port: 9103

spring:
  config:
    import: optional:classpath:config/common.yml
  application:
    name: rank-service

dubbo:
  application:
    name: rank-service
  protocol:
    name: dubbo
    port: 20883
