server:
  port: 9100

spring:
  config:
    import: optional:classpath:config/common.yml
  application:
    name: gateway-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:465}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

dubbo:
  application:
    name: gateway-service
  consumer:
    check: false
    timeout: 3000

logging:
  level:
    root: info
