server:
  port: 9105

spring:
  config:
    import: optional:classpath:config/common.yml
  application:
    name: behavior-consumer
  kafka:
    consumer:
      group-id: behavior-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.rs.behavior.api
        spring.json.value.default.type: com.rs.behavior.api.BehaviorEvent
