server:
  port: 9101

spring:
  config:
    import: optional:classpath:config/common.yml
  application:
    name: recall-service

dubbo:
  application:
    name: recall-service
  protocol:
    name: dubbo
    port: 20881
